version: '3'

services:
  flask:
    build: .
    ports:
    - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    